### PR TITLE
Enable optimizations

### PR DESCRIPTION
**Pull request by PtrMan**

### CODE REVIEW

**Comment by patham9** [comment]
This would make the created executable limited to a certain processor, wouldn't it? Not sure this is worth  the probably 5-10% extra performance.

**Comment by PtrMan** [comment]
just to the processor where its compiled.

We can just enable SSE extensions as an alternative

**Comment by PtrMan** [comment]
AVX should be ideally twice as fast as SSE crap - no idea why you always guess incorrectly.

**Comment by PtrMan** [comment]
I removed the native target for now

**Comment by patham9** [comment]
You think the compiler would automatically  inject AVX instructions? Or what's the point in your argument?

**Comment by patham9** [comment]
Looks good, thank you!

**Comment by PtrMan** [comment]
It will emit AVX instructions if its compiled on a AVX processor with -march=native

**Comment by patham9** [comment]
Can you prove that this actually happens in the output assembly? If that's true, ANSNA should run a lot faster when compiled with -march-native, not just by 5-10%, more like twice as fast, given that AVX instructions will be 256 bit?

**Comment by PtrMan** [comment]
I tried it in godbolt already - lets recap https://godbolt.org/z/-4UCML

**Comment by patham9** [comment]
awesome, let's add march=native by default for now! :)

**Pull request merged**
